aspnet/Security

src/Microsoft.AspNet.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs, src/Microsoft.AspNet.Security.OpenIdConnect/Resources.resx, src/Microsoft.AspNet.Security/Infrastructure/AuthenticationHandler.cs
OpenIdConnect set Ticket.Principal, get identity from there.
=> ChallengeContext will be null with [Authorize] attribute

NuGet.Config
Wilson packages are now part of aspnet myget feeds. Removing azure feed from restore sources.
=> Removing the AzureAD feed from security repo

src/Microsoft.AspNet.Security.OpenIdConnect/project.json
OpenIdconnect project is betting on the dependencies included by Microsoft.IdentityModel.Protocol.Extensions for the types that are referenced directly in this library but not used in Protocol.Extensions library.
This change is to enable Wilson clean up its unused dependencies.
@brentschmaltz @Tratcher @muratg
=> Adding necessary dependencies to OpenIdConnect directly

test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs
https://github.com/aspnet/HttpAbstractions/issues/231
@GrabYourPitchforks
=> Temporarily skipping a couple of tests to work around Url encoder bug

src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationOptions.cs, src/Microsoft.AspNet.Authentication.Facebook/FacebookAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.MicrosoftAccount/Notifications/MicrosoftAccountAuthenticatedContext.cs, src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OAuthBearer/OAuthBearerAuthenticationOptions.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs, src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication/CertificateSubjectPublicKeyInfoValidator.cs, src/Microsoft.AspNet.Authentication/CertificateThumbprintValidator.cs
Using the "nameof" operator instead of magic string will help us if the variable change in the future for whatever the reason
=> Using [NotNull] and  'nameof' operator

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/Resources.Designer.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/Resources.resx, src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json, src/Microsoft.AspNet.Authentication/AuthenticationServiceCollectionExtensions.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs
Fixes https://github.com/aspnet/Security/issues/212.
For the first attempt, I opted for the "hybrid" approach (https://github.com/aspnet/Security/issues/212#issuecomment-112533342): the distributed cache is retrieved from the options when available, and from the DI container when the user didn't provide his own cache.
Storing nonces in the distributed cache is not enabled by default but can easily be using `StoreNoncesInCache`. I'm not super satisfied with the name, so don't hesitate to suggest another one :smile: 
FYI, I haven't been able to use the `OpenIdConnectSample` app because it delegates authentication to AAD, that doesn't allow me to log in using my live.com account. I worked around this issue using `AspNet.Security.OpenIdConnect.Server` …
=> Replace INonceCache by IDistributedCache

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs
Fixes https://github.com/aspnet/Security/issues/217
/cc @brentschmaltz @HaoK @Tratcher
=> Add response_mode=query support for OpenID Connect

src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationOptions.cs, src/Microsoft.AspNet.Authentication.OAuthBearer/OAuthBearerAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OAuthBearer/OAuthBearerAuthenticationOptions.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs, test/Microsoft.AspNet.Authentication.Test/OAuthBearer/OAuthBearerMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
This pull request fixes a few things that were not solved by @brentschmaltz's PR (https://github.com/aspnet/Security/pull/112).
Please note that it's still a WIP and that I'll probably add more commits.
/cc @HaoK @brentschmaltz
=> Incorporate community feedback from https://github.com/aspnet/Security/pull/112

samples/OpenIdConnectSample/Startup.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMethod.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
Fixes https://github.com/aspnet/Security/issues/295.
@Eilon as promised in my last mail, here are the first bits of the new POST authentication/authorization requests support for OIDC.
/cc @Eilon @HaoK @Tratcher
=> Support POST OpenID Connect authentication/logout requests

src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.JwtBearer/project.json, src/Microsoft.AspNet.Authentication.MicrosoftAccount/project.json, src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OAuth/project.json, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json, src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationMiddleware.cs, src/Microsoft.AspNet.Authentication.Twitter/project.json
#415 
HttpClientHandler defaults to the new CurlHandler on Mac and Linux, and to WinHttpHandler on Windows.
@BrennanConroy @muratg
=> Use a cross-platform friendly HttpClient for CoreCLR.

test/Microsoft.AspNet.Authentication.Test/Cookies/CookieMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/DataHandler/Base64UrlTextEncoderTests.cs, test/Microsoft.AspNet.Authentication.Test/Facebook/FacebookMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/MicrosoftAccount/MicrosoftAccountMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/Twitter/TwitterMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/project.json, test/Microsoft.AspNet.Authorization.Test/project.json
* removed Shouldy as a dependency from all tests
* could not enable coreclr50 due to remaining incompatibility with moq, Uri.GetLeftPart(...), UriPartial, et al
#420
=> Removed references to Shouldly

src/Microsoft.AspNet.Authorization/AllowAnonymousAttribute.cs, src/Microsoft.AspNet.Authorization/AuthorizationPolicy.cs, src/Microsoft.AspNet.Authorization/IAllowAnonymous.cs
https://github.com/aspnet/Mvc/issues/3246
@rynowak @Eilon
=> Moving AllowAnonymous attribute from MVC

samples/OpenIdConnectSample/Startup.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectMiddleware.cs, src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs, test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
#455 @HaoK @brentschmaltz @tushargupta51 @PinpointTownes @leastprivilege
From what we can tell RedirectUri can be correctly generated in most scenarios, and if you really need to override it you can do so in the events. This brings OIDC in line with the other middleware and requires less configuration parameter.
=> Remove RedirectUri from OIDC, use CallbackPath.

test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs, test/Microsoft.AspNet.Authentication.Test/Twitter/TwitterMiddlewareTests.cs
It looks like HttpClient on Windows extracts the base exception from an AggregateException in a response, while Mono doesn't. So we need to look at the base exception of whatever exception is returned when an error is expected in a response. This works for non-aggregate exceptions because GetBaseException() returns the exception itself in that case.
cc @Tratcher
=> Fix some authentication unit tests failing on Linux and OS X.

samples/SocialSample/Startup.cs, src/Microsoft.AspNet.Authentication.Facebook/FacebookDefaults.cs, src/Microsoft.AspNet.Authentication.Facebook/FacebookHandler.cs, src/Microsoft.AspNet.Authentication.Facebook/FacebookOptions.cs, test/Microsoft.AspNet.Authentication.Test/Facebook/FacebookMiddlewareTests.cs
#565, #435
1. They now use a standard JSON instead of a custom Form response from the TokenEndpoint.
2. Added support for requesting non-default Fields like e-mail.
@HaoK
/cc: @MikeWasson @AlexTo @hajjat @Jayman1305 @chris02031 @dotnetshadow
=> Update facebook APIs to v2.5.

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNet.Authentication.Twitter/TwitterHandler.cs, src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs, src/Microsoft.AspNet.Authentication/RemoteAuthenticationHandler.cs
Reacting to https://github.com/aspnet/Logging/pull/314.
Tested locally.
=> Reacting to verbose rename

src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs
Just fixing a typo in an AuthenticationHandler.cs log message HttContext.User merged...=>HttpContext.User merged…
=> Fix Typo in a Log Message

src/Microsoft.AspNetCore.Authorization/project.json
- The authorization stack doesn't depend on AspNetCore at all really
This brings up an interesting question, why is it tied to ASP.NET at all? Shouldn't the AuthorizationContext flow the HttpContext as well? 
/cc @HaoK @blowdart @Tratcher @lodejard
=> Remove unused dependency

samples/SocialSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleMiddleware.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleOptions.cs, src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountMiddleware.cs, src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountOptions.cs
#614 @PinpointTownes @brockallen @HaoK @Eilon 
Google and MSA require scopes by default so we provide a few. However they also send an ok error message if you clear the default scopes so we're not checking for missing scopes in the constructor.
OIDC already works like this.
=> Standardize the pattern for scope defaults.

src/Microsoft.AspNetCore.Authentication.OAuth/OAuthOptions.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
Make sure scope list only has unique elements.
- Change  OAuthOptions to use Hashset for Scope list
- Change OpenIDConnectOptions to use HashSet for scope list
- Change OpenIDConnectOptions  to new options pattern for scope defaults
No known APIs break with duplicate scope values.
However Facebook breaks for duplicate field values so it seems a good idea to guard against duplicate scope values as well  using the same methodology.
It is quite possible that a future API may not be so accommodating of duplicate values.
PS I cant get tests running but tested used social sample and OpenIDConnect sample (Google authority)
=> Ensure scope has no duplicates

samples/OpenIdConnectSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
#456 
@vibronet @brentschmaltz @tushargupta51 @PinpointTownes @muratg 
Note I will do a followup PR where we can resolve some of the event TODOs in this one. I wanted to get most of the auth mechanics taken care of first.
=> Unify OIDC Code/IdToken/Hybride flows.

Security.sln, samples/OpenIdConnect.AzureAdSample/AuthPropertiesTokenCache.cs, samples/OpenIdConnect.AzureAdSample/OpenIdConnect.AzureAdSample.xproj, samples/OpenIdConnect.AzureAdSample/Properties/launchSettings.json, samples/OpenIdConnect.AzureAdSample/Startup.cs, samples/OpenIdConnect.AzureAdSample/project.json, samples/OpenIdConnect.AzureAdSample/wwwroot/web.config, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/AuthorizationCodeReceivedContext.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
#690 
This allows developers to either customize the request to the token endpoint, or to take complete control and make the request themselves. This gives us enough flexibility to plug in something like ADAL for their advanced redemption and storage scenarios. We'll add an ADAL specific sample as part of a following discussion.
@vibronet @brentschmaltz @tushargupta51 @PinpointTownes @HaoK @muratg
=> Enable custom OIDC authorization code redemption.

src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyMiddleware.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookiePolicyTests.cs
- see issue aspnet/HttpAbstractions#561 and pull aspnet/HttpAbstractions#589
=> React to HttpAbstractions change: No features in `.Internal` namespace

samples/OpenIdConnectSample/Startup.cs, samples/SocialSample/Properties/launchSettings.json, samples/SocialSample/Startup.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
#667 - Authenticated but not authorized infinite loop
#801 - Authenticate remote provider by name
When a user lacks a specific claim the authorization service issues a Challenge. For Bearer or Cookies they accept this challenge, verify that they produced the identity, and switch to Forbid. This isn't happening for the remote providers because they do not maintain the identity, they delegate that to Cookies. As such they end up in an infinite challenge loop. See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L310-L332 for reference on Challenge behaviors.
Similarly, `[Authorize(ActiveAuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]` doesn't work because the remote auth handler does not store the identity …
=> Handle authorize and forbid for redirecting handlers.

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationMiddleware.cs, src/Microsoft.Owin.Security.Interop/ChunkingCookieManager.cs, src/Microsoft.Owin.Security.Interop/Constants.cs, test/Microsoft.AspNetCore.Authentication.Test/Cookies/Infrastructure/CookieChunkingTests.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookiePolicyTests.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/project.json, test/Microsoft.Owin.Security.Interop.Test/CookieInteropTests.cs
#814 @anurse @HaoK @muratg 
Change ChunkingCookieManager from appending raw headers to appending via the response cookies API. Here are a few side effects:
- Removed the key & value encoding. The lower level will handle this and most of the time no encoding is required. Worst case we loose a little bit of length precision and devs need to lower ChunkSize accordingly.
- Removed the quote handling. Cookie auth never uses quotes.
- Change the format of the first cookie from `key=chunks:2` to `key=chunks-2`. `:` would be escaped by the response cookies API.
=> Rework CookieAuth for compat with CookiePolicy.

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
#780 @nickcam @HaoK @muratg @Eilon 
Katana used DateTime for all of its fields/properties. We've since converted everything to use DateTimeOffset as it more accurately preserves things like time zone. However, we forgot to remove a few conversions like the ones in this PR. It wasn't a compiler break because of the implicit conversion from DateTime to DateTimeOffset, but we were loosing information in the downgrade.
=> Remove obsolete DateTime conversions

src/Microsoft.AspNetCore.Authentication.JwtBearer/Events/JwtBearerChallengeContext.cs, src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs
#776 @vibronet @blowdart @brentschmaltz @HaoK @PinpointTownes @Eilon @muratg 
For a specific set of exceptions, display those exception messages in the response headers to help the consumer report and debug configuration issues. The list of exceptions to report is configurable. Note we're using headers rather than the body because the auth middleware is never in control of the response body.
Example:
```
Content-Length:0
Date:Wed, 25 May 2016 20:54:58 GMT
Server:Kestrel
WWW-Authenticate:Bearer
X-Authentication-Failure:IDX10214: Audience validation failed. Audiences: '63a87a83-64b9-4ac1-b2c5-092126f8474f'. Did not match:  validationParameters.ValidAudience: '63a87a83-64b9-4ac1-b2c5-092126f8474f-wrongaudiance' or validationParameters.ValidAudiences: 'null'
```
=> Show some JwtBearer errors in response headers

src/Microsoft.AspNetCore.Authentication.JwtBearer/Events/JwtBearerChallengeContext.cs, src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs, src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerOptions.cs, test/Microsoft.AspNetCore.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs
We had agreed on the fact an option allowing to remove the error details from the WWW-Authenticate header was important, but it looks like it was not added by @Tratcher in his PR.
https://github.com/aspnet/Security/issues/776#issuecomment-210263382
/cc @Eilon @HaoK @Tratcher
=> Add a new IncludeErrorDetails option to prevent the JWT middleware from returning error/error_description

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs, src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerOptions.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthOptions.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterOptions.cs, src/Microsoft.AspNetCore.Authentication/AuthenticationOptions.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
Fixes #855, which documents a bug where the `RemoteAuthenticationTimeout` (intended to be used for a correlation cookie) also ends up getting used for the `ExpiresUtc` value of the `AuthenticationProperties` of the actual authentication ticket that gets issued. 
I did not see a generic set of tests for `RemoteAuthenticationHandler` so I refrained from adding a test for now.
=> Remote auth expiration fix

src/Microsoft.AspNetCore.Authorization/AuthorizationPolicy.cs, src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationPolicyProvider.cs
`System.Linq.OfType<>` allocates in order to create an enumerable. Here we've modified the function so as not to do that.
=> Remove OfType allocations

src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs, src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountHandler.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
Address issue #53 
Error message now:
The `GoogleHandler` throws when the response from back channel is out of 2XX range. The exception neither provides sufficient information for user to correct the error or is handled gracefully in `OAuthHandler`
The PR contains two commit. The first one is purely for refactoring and readability improvement. For the actual logic change you can focus on the [second commit](https://github.com/aspnet/Security/commit/967c7cdeb6838368ac775a526b84abd164dd6fae)
=> Handle  the remote authentication failure gracefully

src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationPolicyProvider.cs
Make the warning about the behavior dependency MVC has on DefaultAuthorizationPolicyProvider a bit more explicit.
CC @Eilon, @rynowak, @HaoK, and @blowdart for review.
=> Modify warning about policy behavior

test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/Infrastructure/TestDefaultValues.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectConfigurationTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
1. Move configuration related tests to their own class;
2. Add tests to cover missing options scenarios;
3. Add TestDefaultValues class for default values used in OpenId connect
tests.
Related: https://github.com/aspnet/Security/issues/772
/cc @Tratcher
=> Update OpenId Connect tests

src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/Google/GoogleMiddlewareTests.cs
#859 @Haok
This prevents `[Authorize("Github")]` from returning an identity produced by Facebook, etc. when they share a cookie middleware.
=> Discriminate between providers when sharing an auth cookie

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectChallengeTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
#903 @HaoK @brentschmaltz @PinpointTownes 
This helps users discover middleware configuration errors that may otherwise result in infinite challenge redirects.
=> Ensure redirect uris can be generated

samples/CookieSample/Properties/launchSettings.json, samples/CookieSessionSample/Properties/launchSettings.json, samples/JwtBearerSample/Properties/launchSettings.json, samples/OpenIdConnect.AzureAdSample/Properties/launchSettings.json, samples/OpenIdConnectSample/Properties/launchSettings.json, samples/SocialSample/Properties/launchSettings.json
VS 2017 changes the launch url mechanics for self-host. Before we set launchUrl and ASPNETCORE_URLS, but now we only need to set applicationUrl and VS will set the other two from that value.
Note most of these projects need a specific port because that's what's registered with the 3rd party providers like Facebook.
=> Update launchSettings for new VS 2017 rules

test/Microsoft.AspNetCore.Authentication.Test/Microsoft.AspNetCore.Authentication.Test.csproj, test/Microsoft.AspNetCore.Authorization.Test/Microsoft.AspNetCore.Authorization.Test.csproj, test/Microsoft.AspNetCore.ChunkingCookieManager.Sources.Test/Microsoft.AspNetCore.ChunkingCookieManager.Sources.Test.csproj, test/Microsoft.AspNetCore.CookiePolicy.Test/Microsoft.AspNetCore.CookiePolicy.Test.csproj, test/Microsoft.Owin.Security.Interop.Test/Microsoft.Owin.Security.Interop.Test.csproj
- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
- build tests for desktop .NET only on Windows
- except Microsoft.Owin.Security.Interop.Test; will need to skip that for non-Windows some other way
=> Bump test projects up to .NET 4.5.2

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectChallengeTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/TestSettings.cs
Fixes https://github.com/aspnet/Security/issues/1035.
/cc @Eilon @Tratcher @brentschmaltz @polita
=> Add an opt-out DisableTelemetry option in the OpenID Connect middleware

test/Microsoft.AspNetCore.Authentication.Test/Facebook/FacebookMiddlewareTests.cs, test/Microsoft.AspNetCore.Authentication.Test/Google/GoogleMiddlewareTests.cs, test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccount/MicrosoftAccountMiddlewareTests.cs
React to aspnet/DataProtection#203
@Eilon 
Merging soon to unblock build
=> React to Data Protection refactor

build/dependencies.props, test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs, test/Microsoft.AspNetCore.Authentication.Test/Microsoft.AspNetCore.Authentication.Test.csproj, test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs, test/Microsoft.AspNetCore.Authentication.Test/TicketSerializerTests.cs, test/Microsoft.AspNetCore.Authentication.Test/TokenExtensionTests.cs, test/Microsoft.AspNetCore.Authorization.Test/DefaultAuthorizationServiceTests.cs, test/Microsoft.AspNetCore.Authorization.Test/Microsoft.AspNetCore.Authorization.Test.csproj, test/Microsoft.AspNetCore.ChunkingCookieManager.Sources.Test/Microsoft.AspNetCore.ChunkingCookieManager.Sources.Test.csproj, test/Microsoft.AspNetCore.CookiePolicy.Test/Microsoft.AspNetCore.CookiePolicy.Test.csproj
Updating to xunit 2.3 (which includes xunit.analyzers) revealed some methods that should have been marked `[Fact]` and some asserts that were backwards.
=> Update test framework versions and fix issues with tests

samples/CookieSample/Startup.cs, samples/CookieSessionSample/Startup.cs, samples/JwtBearerSample/Startup.cs, samples/OpenIdConnectSample/OpenIdConnectSample.csproj, samples/OpenIdConnectSample/Program.cs, samples/SocialSample/Program.cs, samples/SocialSample/SocialSample.csproj, samples/SocialSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthExtensions.cs
@HaoK many of the samples are broken. I noticed while investigating https://github.com/aspnet/Security/issues/1224 (which doesn't repro in dev).
=> Make samples work. Fix AddOAuthAuthentication extension.

shared/Microsoft.AspNetCore.ChunkingCookieManager.Sources/ChunkingCookieManager.cs, src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs, src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs, src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyMiddleware.cs, src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyOptions.cs, test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs, test/Microsoft.AspNetCore.ChunkingCookieManager.Sources.Test/CookieChunkingTests.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookiePolicyTests.cs
Addresses #908 Reacting to https://github.com/aspnet/HttpAbstractions/pull/843. Still need to update defaults.
=> Add SameSitePolicy to CookiePolicyMiddleware

.gitignore, samples/OpenIdConnect.AzureAdSample/Program.cs, src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs, src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyOptions.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookiePolicyTests.cs
Addresses #1231  Need to test this with the auth samples before merging.
=> Update default settings for SameSite

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/OpenIdConnectEvents.cs
=> Doc comments for OnRedirectToIdentityProvider

samples/OpenIdConnect.AzureAdSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectTests.cs
@PinpointTownes 
The usage of PostLogoutRedirectUri changed in 1.1 so that it no longer aligned with the spec term field. SignedOutCallbackPath has been used since 1.1 for the post_logout_redirect_uri protocol field. Renaming PostLogoutRedirectUri now to avoid confusion.
=> Rename PostLogoutRedirectUri to avoid spec confusion

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterOptions.cs, src/Microsoft.AspNetCore.Authentication/Internal/RequestPathBaseCookieBuilder.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs, test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectTests.cs
Addresses https://github.com/aspnet/HttpAbstractions/issues/853.
Uses the new CookieBuilder API added here: https://github.com/aspnet/HttpAbstractions/pull/882
Part 1- look for a separate PR to remove duplication from CookieAuthenticationOptions.
=> Replace configure method on TwitterOptions and OpenIdConnectOptions with CookieBuilder

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs, src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs, src/Microsoft.AspNetCore.Authentication.Cookies/Microsoft.AspNetCore.Authentication.Cookies.csproj, test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs
`CookieAuthenticationOptions.Cookie.Expiration` is conceptually different from `CookieAuthenticationOptions.ExpireTimeSpan`.
Un-oboleting the property and updating xmldocs.
=> Revert obsoleting CookieAuthenticationOptions.ExpireTimeSpan

src/Microsoft.AspNetCore.Authentication.JwtBearer/Events/MessageReceivedContext.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/MessageReceivedContext.cs
My first PR. Correcting a typo in the XML docs of the MessageReceivedContext.Token property. I've used these libraries extensively in recent weeks and this typo was bugging me.
=> Corrected typos in XML Docs in MessageReceivedContext (JwtBearer and OpenIdConnect)

test/Microsoft.AspNetCore.CookiePolicy.Test/CookiePolicyTests.cs
Reacts to https://github.com/aspnet/HttpAbstractions/commit/594f55947f4c1d0a9d3122e3f39bcfa81199b12a
We now preserve Secure, HttpOnly, and SameSite on Delete.
=> Reacting to ResponseCookie Delete changes

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs
Fix a copy & paste error in an `[Obsolete]` attribute within `CookieAuthenticationOptions.cs`.
/cc: @natemcmaster
=> Recommend CookieBuilder.HttpOnly instead of CookieBuilder.SameSite

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs
Fixes the messaged shown to developers when they are updating their applications to 2.0. Bad idea to set the domain with some random naming text.
=> Fix obsolete warning message

src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs, src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs, src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountHandler.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs
Easy half of https://github.com/aspnet/Security/issues/1218
Most are public already, so should be harmless being consistent with these.
Extensibility, aka 
`MyGoogle<MyGoogleOptions> : GoogleHandler` is something we can look at later
@Tratcher
=> Make all handlers public

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/OpenIdConnectEvents.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/LoggingExtensions.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectEventTests.cs
#942 Back-filling an event we couldn't add before due to interface breaking change issues. The event interface was removed in 2.0 so we can add the events we were missing.
@PinpointTownes
=> Add the SignedOutCallbackRedirect event for OIDC

samples/SocialSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, src/Microsoft.AspNetCore.Authentication/Events/RemoteFailureContext.cs, src/Microsoft.AspNetCore.Authentication/HandleRequestResult.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectEventTests.cs, test/Microsoft.AspNetCore.Authentication.Test/TwitterTests.cs
#1188 Requires https://github.com/aspnet/HttpAbstractions/pull/889
User state for the login is flown via auth properties, but these aren't available in the OnRemoteFailure event. To add them we need to flow them via the AuthResult.
If this works out then we may use it to flow additional data for #1178. The difference is that the data in #1178 isn't a consistent data structure across handlers.
/cc: @brockallen
=> Add AuthenticationProperties to HandleRequestResult and RemoteFailureContext

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
- Set prompt parameter to value set in Options in OpenIdConnectHandler.HandleChallengeAsync()
- See http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest for expected behavior
Addresses #1398
=> Added ability to set prompt parameter in OpenIdConnectOptions

src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationHandler.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationOptions.cs, test/Microsoft.AspNetCore.Authentication.WsFederation.Test/WsFederationTest.cs
#1443 This adds the standard correlation cookie requirement to WsFed. If wctx or cookie are missing then the request will be rejected. AllowUnsolicitedLogins can be used to opt out of this check.
@brentschmaltz @PinpointTownes
=> Block unsolicited wsfed logins by default.

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
#1353 -1 is an invalid value for the Expires header, it should be a date in the past.
=> Use a compliant Expires header value for expiration.

shared/Microsoft.AspNetCore.ChunkingCookieManager.Sources/ChunkingCookieManager.cs, src/Microsoft.Owin.Security.Interop/ChunkingCookieManager.cs, test/Microsoft.AspNetCore.ChunkingCookieManager.Sources.Test/CookieChunkingTests.cs
#1349 In practice customers end up disabling this option (if they find it).
=> Don't throw for partial cookies

src/Microsoft.AspNetCore.Authentication.OAuth/Claims/JsonKeyClaimAction.cs, test/Microsoft.AspNetCore.Authentication.Test/ClaimActionTests.cs
Claims like role might come in a form of an array with multiple values. When using the default Oidc MW role option isn't mapped by default, so that mapping has to be added.
```o.ClaimActions.Add(new JsonKeyClaimAction("role", "role", "role"));```
The default mappers only process the single string value claims. This can be useful for any multivalue claim.
In the case of roles, as each claim is mapped to the same key, User.IsInRole works as expected. If you expand the list of claims for ClaimsIdentity it would looks something like this
```
{name: user}
{role: Foo}
{role: Bar}
```
=> Added support for multiple values (arrays) in default claim action

src/Microsoft.AspNetCore.Authentication.WsFederation/Events/WsFederationEvents.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationHandler.cs, test/Microsoft.AspNetCore.Authentication.WsFederation.Test/WsFederationTest.cs
#1520 Auth 2.0 introduce the ability to resolve the events class from DI. This change adds that to the WsFed handler. It also adds virtual methods to the event class to support overriding.
@PinpointTownes @lzandman
=> Update WsFed to use the 2.0 event structure

src/Microsoft.AspNetCore.Authentication.WsFederation/Events/RemoteSignoutContext.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/Events/WsFederationEvents.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/LoggingExtensions.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationHandler.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationOptions.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationPostConfigureOptions.cs, test/Microsoft.AspNetCore.Authentication.WsFederation.Test/WsFederationTest.cs
#1425 This mirrors the remotely initiated signout support in OIDC.
@leastprivilege
=> Implement WsFed remote signout cleanup

src/Microsoft.AspNetCore.Authentication.JwtBearer/LoggingExtensions.cs
_tokenValidationFailed format string includes the JWT token followed by a period, which if a dev troubleshooting copies incorrectly to the EOL will make the JWT invalid. (https://github.com/aspnet/Security/blob/a9482d1d03fc22f62e42cf31b8adb32c5550835e/src/Microsoft.AspNetCore.Authentication.JwtBearer/LoggingExtensions.cs#L19)
Current: Failed to validate the token eyJhbGc.......HCwFmw.
Proposed: Failed to validate the token eyJhbGc.......HCwFmw
=> Updated logging extension to remove the period on ValidationFailed

Security.sln, samples/CookiePolicySample/CookiePolicySample.csproj, samples/CookiePolicySample/Program.cs, samples/CookiePolicySample/Properties/launchSettings.json, samples/CookiePolicySample/Startup.cs, shared/Microsoft.AspNetCore.ChunkingCookieManager.Sources/ChunkingCookieManager.cs, src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterOptions.cs, src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs, src/Microsoft.AspNetCore.CookiePolicy/AppendCookieContext.cs, src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyMiddleware.cs, src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyOptions.cs, src/Microsoft.AspNetCore.CookiePolicy/DeleteCookieContext.cs, src/Microsoft.AspNetCore.CookiePolicy/ResponseCookiesWrapper.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookieConsentTests.cs
Here is the baseline feature for discussion. CookiePurpose needs attention, we need to decide what the categories are, if there's a default policy allowing some categories, etc..
I updated CookieAuth to work, but not any of the remote auth providers.
Depends on https://github.com/aspnet/HttpAbstractions/commit/0bd9bd8f76665f64c3e412de94f10fe3703aca50
=> Add consent policies to CookiePolicy

src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/TwitterTests.cs
Replaces https://github.com/aspnet/Security/pull/1582
This is what happens when a new user clicks cancel on Twitter's authorization page.
=> Detect remote denails for Twitter accounts

Security.sln, src/Microsoft.AspNetCore.CookiePolicy/ResponseCookiesWrapper.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookieConsentTests.cs
#1590 @DamianEdwards 
This reduces the amount of work that needs to be done in the template when they want to set the consent cookie on the client via javascript.
See https://github.com/aspnet/templating/pull/213/files#diff-947841bf97b345569d23143ef4af84af
This requires https://github.com/aspnet/HttpAbstractions/commit/ce6934126513f1da9e46b8d695fedb2ddf261ae1
=> Implement ITrackingConsentFeature.CreateConsentCookie()

src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationHandler.cs, src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationOptions.cs, test/Microsoft.AspNetCore.Authentication.WsFederation.Test/WsFederationTest.cs
#1581 @brockallen can you build this branch and try it? I don't expect to ship another preview.
The prior design and defaults were set up for AAD but didn't work for ADFS. ADFS usage is more likely so we'll use defaults that work there.
Also AAD's single sign out doesn't work right if you have multiple reply urls, the cleanup messages get sent to a random reply url.
=> Rework WsFed RemoteSignOutPath logic to work with ADFS 

samples/WsFedSample/WsFedSample.csproj, src/Microsoft.AspNetCore.Authentication.WsFederation/Microsoft.AspNetCore.Authentication.WsFederation.csproj, test/Microsoft.AspNetCore.Authentication.WsFederation.Test/Microsoft.AspNetCore.Authentication.WsFederation.Test.csproj
Rebased on 2.0.1.
Updating the IdentityModel dependency to 5.2.0 RTM. This was our largest ship blocker.
Change the package version to 2.0.0 RTM.
=> WsFed OOB Update versions, dependencies.

test/Microsoft.AspNetCore.CookiePolicy.Test/CookieConsentTests.cs
#1629 The granted cookie and the manually generated cookie should match, but they're created milliseconds apart so the date may drift. I changed the test to a logical equality check instead of a string equality.
=> Fix flaky cookie policy tests 

src/Microsoft.AspNetCore.Authentication.Facebook/FacebookDefaults.cs, test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
#1306 No behavioral changes.
Our current version (2.6) will expire July 13, 2018.
=> Update facebook API version to 2.12

samples/CookiePolicySample/Program.cs, src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyMiddleware.cs, src/Microsoft.AspNetCore.CookiePolicy/LoggingExtensions.cs, src/Microsoft.AspNetCore.CookiePolicy/Microsoft.AspNetCore.CookiePolicy.csproj, src/Microsoft.AspNetCore.CookiePolicy/ResponseCookiesWrapper.cs, test/Microsoft.AspNetCore.CookiePolicy.Test/CookiePolicyTests.cs
#1588
I had to work around https://github.com/aspnet/Home/issues/2871 by putting the constructors in a specific order.
@blowdart I did find an is issue where a CookieSecurePolicy.SameAsRequest policy would cause a Secure cookie to be downgraded if it was being sent over HTTP rather than HTTPS. However, users shouldn't be sending secure cookies over HTTP anyways. I changed it to make sure it never downgrades.
=> Add CookiePolicy logging 

test/Microsoft.AspNetCore.Authorization.Test/AuthorizationPolicyFacts.cs
Renamed namespace "Microsoft.AspNetCore.Authroization.Test" to "Microsoft.AspNetCore.Authorization.Test".
- Build and tests are passing.
- (This is my first PR)
=> Fix spelling in AuthorizationPolicyFacts.cs

samples/OpenIdConnectSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.OAuth/Claims/ClaimActionCollectionMapExtensions.cs, src/Microsoft.AspNetCore.Authentication.OAuth/Claims/MapAllClaimsAction.cs, test/Microsoft.AspNetCore.Authentication.Test/ClaimActionTests.cs
#1609 @leastprivilege @brockallen how does this look? It covers your asks in three parts:
- Clear the JWT claims type map.
- Map all claims
- bulk delete protocol claims
=> Add ClaimActions for bulk add and remove

samples/OpenIdConnectSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleChallengeProperties.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthChallengeProperties.cs, src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectChallengeProperties.cs, src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs, test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs, test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccountTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OAuthChallengePropertiesTest.cs, test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectChallengeTests.cs, test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/TestSettings.cs
This is a follow-up to #1401 which introduced the ability to specify the `prompt` for OpenID Connect authentication requests to the authentication provider. As per [the spec](http://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1), this will control how the authentication provider will behave.
In the original pull request, this was added as a global option for the authentication scheme. However, there are use cases where specifying the `prompt` on specific requests would be very useful. In particular, the `prompt=login` value will request a *“reauthentication”*, making this a useful thing to make the user confirm that they can actually log in with the authentication provider; but having this as a global option would be too much.
This pull requests adds the ability to …
=> Add a way to overwrite the OAuth parameters on challenge requests (e.g. "scope", or the OIDC "prompt")

src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs
https://github.com/aspnet/Security/issues/1695
Tested in my app & working
=> Correct Twitter OAuth signing code. Also, refactor copy/pasted code & make reusable TwitterHandler.ExecuteRequestAsync public

src/Microsoft.AspNetCore.Authentication/HandleRequestResult.cs, test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs
#1809
I've cherry picked the fix for the regression (#1767) back from 2.2 to 2.1. 
I've also cherry picked #1759 to provide test infrastructure, and added #1768 to cover this specific scenario.
=> Patch 2.1 JwtBearer SaveToken

samples/SocialSample/Startup.cs, src/Microsoft.AspNetCore.Authentication.Facebook/FacebookDefaults.cs, src/Microsoft.AspNetCore.Authentication.Facebook/FacebookOptions.cs, src/Microsoft.AspNetCore.Authentication.Google/GoogleDefaults.cs, src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountDefaults.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterDefaults.cs, src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs, test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
#92 Facebook has changed its API version from v2.12 to v3.1. It has also removed the public_profile scope, this permission is available by default. See https://developers.facebook.com/docs/graph-api/changelog/version3.0#login
None of the other providers have made any relevant API changes. I did add some doc links for next time.
=> Update Facebook to v3.1 endpoints

.gitignore, Security.sln, benchmarks/Microsoft.AspNetCore.Security.Performance/AuthorizationMiddlewareBenchmark.cs, benchmarks/Microsoft.AspNetCore.Security.Performance/AuthorizationPolicyBenchmark.cs, benchmarks/Microsoft.AspNetCore.Security.Performance/Microsoft.AspNetCore.Security.Performance.csproj, benchmarks/Microsoft.AspNetCore.Security.Performance/Properties/AssemblyInfo.cs, benchmarks/Microsoft.AspNetCore.Security.Performance/readme.md, build/dependencies.props, src/Microsoft.AspNetCore.Authorization/AuthorizationPolicy.cs, src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationPolicyProvider.cs
Used by AuthorizationMiddleware. Want to avoid allocations when there is no policy to evaluate.
Hide whitespace for best reviewing experience.
On https://github.com/aspnet/Security/pull/1894
=> Eliminate allocations in AuthorizationPolicy.CombineAsync with no policy

src/Microsoft.AspNetCore.Authorization/AuthorizationPolicyBuilder.cs
The description of the pram roles feels ambiguous. Make it clear that the user should belong to one of the roles and not all of them.
As documented: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.1
=> Change description of role in RequireRole method
