aspnet/Security

src/Microsoft.AspNet.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs

This fixes bug : https://github.com/aspnet/Security/issues/144
@brentschmaltz

Creating authentication ticket by passing in a principal

---

samples/OpenIdConnectSample/OpenIdConnectSample.kproj
src/Microsoft.AspNet.Security.OAuthBearer/Microsoft.AspNet.Security.OAuthBearer.kproj
src/Microsoft.AspNet.Security.OpenIdConnect/Microsoft.AspNet.Security.OpenIdConnect.kproj

Removing the AzureAD feed from security repo

---

build.cmd
build.sh
samples/CookieSample/project.json
samples/CookieSessionSample/project.json
samples/OpenIdConnectSample/project.json
samples/SocialSample/project.json
src/Microsoft.AspNet.Authentication.Cookies/project.json
src/Microsoft.AspNet.Authentication.Facebook/project.json
src/Microsoft.AspNet.Authentication.Google/project.json
src/Microsoft.AspNet.Authentication.MicrosoftAccount/project.json
src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationMiddleware.cs
src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationOptions.cs
src/Microsoft.AspNet.Authentication.OAuth/project.json
src/Microsoft.AspNet.Authentication.OAuthBearer/OAuthBearerAuthenticationMiddleware.cs
src/Microsoft.AspNet.Authentication.OAuthBearer/OAuthBearerAuthenticationOptions.cs
src/Microsoft.AspNet.Authentication.OAuthBearer/project.json
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json
src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationMiddleware.cs
src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationOptions.cs
src/Microsoft.AspNet.Authentication.Twitter/project.json
src/Microsoft.AspNet.Authentication/CertificateSubjectKeyIdentifierValidator.cs
src/Microsoft.AspNet.Authentication/CertificateSubjectPublicKeyInfoValidator.cs
src/Microsoft.AspNet.Authentication/CertificateThumbprintValidator.cs
src/Microsoft.AspNet.Authentication/ICertificateValidator.cs
src/Microsoft.AspNet.Authentication/project.json
src/Microsoft.AspNet.Authorization/project.json
test/Microsoft.AspNet.Authentication.Test/project.json
test/Microsoft.AspNet.Authorization.Test/project.json

Prepping to be merged once ready.

Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

---

samples/CookieSessionSample/MemoryCacheSessionStore.cs
samples/CookieSessionSample/project.json

Dependent on https://github.com/aspnet/Caching/pull/49/files
@muratg

React to Caching package rename

---

samples/OpenIdConnectSample/Startup.cs
samples/OpenIdConnectSample/wwwroot/placeholder.html

Fixed the sample. 
@HaoK signed off on this change in my office. 
@brentschmaltz @danroth27 @muratg

Fixing the OpenIdConnect sample

---

src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json

@brentschmaltz @muratg 
Fixes #191

Add a description for the OpenIdConnect package

---

build.sh
samples/SocialSample/Startup.cs

https://github.com/aspnet/dnx/issues/1473

Remove k command and use dnx instead

---

src/Microsoft.AspNet.Authentication.OAuthBearer/project.json
src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json

@tushargupta51 @brentschmaltz @muratg @Eilon

Changing Wilson package versions to beta4

---

samples/CookieSample/Startup.cs
samples/CookieSessionSample/Startup.cs
samples/OpenIdConnectSample/Startup.cs
samples/SocialSample/Startup.cs
src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationMiddleware.cs
src/Microsoft.AspNet.Authentication.Cookies/CookieServiceCollectionExtensions.cs
src/Microsoft.AspNet.Authentication.Cookies/Infrastructure/ChunkingCookieManager.cs
src/Microsoft.AspNet.Authentication.Cookies/project.json
test/Microsoft.AspNet.Authentication.Test/Cookies/CookieMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/Cookies/Infrastructure/CookieChunkingTests.cs
test/Microsoft.AspNet.Authentication.Test/Facebook/FacebookMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/MicrosoftAccount/MicrosoftAccountMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/Twitter/TwitterMiddlewareTests.cs

Use common cookie header formatters.

---

samples/CookieSample/project.json
samples/CookieSessionSample/project.json
samples/OpenIdConnectSample/project.json
samples/SocialSample/project.json
src/Microsoft.AspNet.Authentication.Facebook/project.json
src/Microsoft.AspNet.Authentication.OAuth/project.json
src/Microsoft.AspNet.Authentication.Twitter/project.json
src/Microsoft.AspNet.Authentication/project.json
test/Microsoft.AspNet.Authentication.Test/project.json

Remove unneeded dependencies around DataProtection.

---

src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationHandler.cs
src/Microsoft.AspNet.Authentication.Cookies/Notifications/CookieApplyRedirectContext.cs
src/Microsoft.AspNet.Authentication.Cookies/Notifications/CookieAuthenticationNotifications.cs
src/Microsoft.AspNet.Authentication.Cookies/Notifications/CookieResponseSignInContext.cs
src/Microsoft.AspNet.Authentication.Cookies/Notifications/CookieResponseSignOutContext.cs
src/Microsoft.AspNet.Authentication.Cookies/Notifications/DefaultBehavior.cs

Cleanup cookies (moar var)

---

samples/SocialSample/Startup.cs
samples/SocialSample/project.json

Remove diagnostics sample dependency.

---

src/Microsoft.AspNet.Authentication/SecurityHelper.cs
test/Microsoft.AspNet.Authentication.Test/SecurityHelperTests.cs

Outcome of discussion with @blowdart and @lodejard:
The new merging behavior is the following:
- Respect and preserve the order and all identities of the new ClaimsPrincipal being added.
- Add all existing identities in context.User EXCEPT any that have no claims AND !IsAuthenticated
- Create a new ClaimsPrincipal and copy to it, instead of directly modifying the new principal
cc @davidfowl @Tratcher

Tweak  SecurityHelper.AddUserPrincipal logic

---

samples/SocialSample/Startup.cs

Comment support will be removed from `project.json`
https://github.com/aspnet/dnx/pull/1779

Remove comments from project.json

---

samples/CookieSessionSample/MemoryCacheSessionStore.cs

Reacting to Caching api review changes

---

src/Microsoft.AspNet.Authentication.OAuth/Constants.cs
src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationHandler.cs
src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs

Move Correlation stuff to OAuthHandler

---

src/Microsoft.AspNet.Authorization/AuthorizationServiceExtensions.cs
src/Microsoft.AspNet.Authorization/DefaultAuthorizationService.cs
src/Microsoft.AspNet.Authorization/IAuthorizationHandler.cs
src/Microsoft.AspNet.Authorization/IAuthorizationService.cs
src/Microsoft.AspNet.Authorization/PassThroughAuthorizationHandler.cs
test/Microsoft.AspNet.Authorization.Test/DefaultAuthorizationServiceTests.cs

Remove sync AuthZ APIs

---

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs

#278 @brentschmaltz @muratg @tushargupta51

Additional OIDC message validation.

---

src/Microsoft.AspNet.Authentication/DataHandler/TicketSerializer.cs
test/Microsoft.AspNet.Authentication.Test/DataHandler/TicketSerializerTests.cs

#58 
@Eilon @PinpointTownes @brentschmaltz

Serialize the ClaimsIdentity.BootstrapContext.

---

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs

#390 
@brentschmaltz @PinpointTownes @HaoK

Make the nonce cookie expire.

---

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectMiddleware.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json

#434 
@HaoK @PinpointTownes @brentschmaltz 
cc: @Eilon @muratg

Remove the nonce cache.

---

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs

#147 @HaoK @Eilon 
/cc: @leastprivilege @briandonahue @brockallen

Make OIDC UseTokenLifetime false by default.

---

samples/OpenIdConnectSample/Properties/launchSettings.json
samples/OpenIdConnectSample/Startup.cs
samples/OpenIdConnectSample/project.json
src/Microsoft.AspNet.Authentication.JwtBearer/project.json
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerForTestingAuthenticate.cs

#493 
@muratg @tushargupta51 @brentschmaltz

Upate to IdentityModel beta8 dependencies.

---

samples/OpenIdConnectSample/Startup.cs
samples/OpenIdConnectSample/project.json
samples/OpenIdConnectSample/wwwroot/web.config
src/Microsoft.AspNet.Authentication.JwtBearer/project.json
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json

#506 @tushargupta51 @brentschmaltz @HaoK 
Also update the sample to work with HttpPlatformHandler

Update to Rc1 IdentityModel, update ValidateUserInfoEndpointResponse

---

src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationHandler.cs
src/Microsoft.AspNet.Authentication/DataHandler/ISecureDataFormat.cs
src/Microsoft.AspNet.Authentication/DataHandler/SecureDataFormat.cs
test/Microsoft.AspNet.Authentication.Test/DataHandler/SecureDataFormatTests.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/AuthenticationPropertiesFormaterKeyValue.cs

#263 @HaoK @PinpointTownes
I also manually verified it works with IE (Win10) and WebListener.

Consume ITlsTokenBindingFeature in CookieAuthMiddleware.

---

src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/Properties/Resources.Designer.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/Resources.resx

https://github.com/aspnet/Security/issues/414 and https://github.com/aspnet/Security/issues/418
Also started putting in event ids for logs.
@Tratcher @HaoK

Remove log codes from exception/log messages; don't localize logs

---

src/Microsoft.AspNet.Authentication.Cookies/CookieAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.Cookies/CookieServiceCollectionExtensions.cs
src/Microsoft.AspNet.Authentication.Facebook/FacebookAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.Google/GoogleAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.MicrosoftAccount/MicrosoftAccountAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.OAuth/OAuthAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.Twitter/TwitterAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication/AuthenticationServiceCollectionExtensions.cs
src/Microsoft.AspNet.Authentication/ClaimsTransformationAppBuilderExtensions.cs
src/Microsoft.AspNet.Authorization/AllowAnonymousAttribute.cs
src/Microsoft.AspNet.Authorization/AuthorizationServiceCollectionExtensions.cs
src/Microsoft.AspNet.Authorization/AuthorizeAttribute.cs
src/Microsoft.AspNet.Authorization/IAuthorizeData.cs
src/Microsoft.AspNet.CookiePolicy/CookiePolicyAppBuilderExtensions.cs

Also did some minor renames to match extension method patterns.
@HaoK @blowdart @Tratcher

Add lots of missing doc comments.

---

src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerMiddleware.cs
src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerOptions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectMiddleware.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs

#485 
Something like this @PinpointTownes?
@muratg @Eilon @brentschmaltz @tushargupta51 @blowdart 
(I'll do Bearer once we agree on the fix).

OIDC RequireHttpsMetadata

---

src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerHandler.cs
test/Microsoft.AspNet.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs

#411 @HaoK @PinpointTownes @tushargupta51 @brentschmaltz 
RE: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/312
ISecurityTokenValidator.ValidateToken throws exceptions for any failure such as expired tokens, invalid tokens, etc.. Since these kind of failures will be common we should handle them gracefully.
For AutomaticAuthenticate=true this will raise the AuthenticationFailed event but not throw. It will appear as if there were no credentials provided and the authorization will usually fail with a 401.
The advanced HttpContext.Authentication.AuthenticateAsync API can return the detailed errors.
Would this also make sense for other auth middleware? I'm not sure it would be as useful because they operate primarily with immediate redirects, not …

Handle validation failures from ValidateToken.

---

.travis.yml

@Eilon @pranavkm 
We'll see if they pass...

Enable CoreClr tests on Travis.

---

samples/CookieSample/project.json
samples/CookieSample/wwwroot/web.config
samples/CookieSessionSample/project.json
samples/CookieSessionSample/wwwroot/web.config
samples/OpenIdConnectSample/project.json
samples/SocialSample/Properties/launchSettings.json
samples/SocialSample/project.json
samples/SocialSample/wwwroot/web.config

Several of them were still using Helios.
@HaoK

Update the sample dependencies, commands, etc..

---

src/Microsoft.AspNet.Authentication.Twitter/TwitterHandler.cs
test/Microsoft.AspNet.Authentication.Test/Twitter/TwitterMiddlewareTests.cs

Update the Twitter AuthenticationEndpoint

---

src/Microsoft.AspNet.Authentication.Google/GoogleDefaults.cs
test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs

Update Google token endpoint.

---

Security.sln
samples/JwtBearerSample/JwtBearerSample.xproj
samples/JwtBearerSample/Properties/launchSettings.json
samples/JwtBearerSample/Startup.cs
samples/JwtBearerSample/Todo.cs
samples/JwtBearerSample/project.json
samples/JwtBearerSample/wwwroot/App/Scripts/app.js
samples/JwtBearerSample/wwwroot/App/Scripts/homeCtrl.js
samples/JwtBearerSample/wwwroot/App/Scripts/indexCtrl.js
samples/JwtBearerSample/wwwroot/App/Scripts/todoListCtrl.js
samples/JwtBearerSample/wwwroot/App/Scripts/todoListSvc.js
samples/JwtBearerSample/wwwroot/App/Scripts/userDataCtrl.js
samples/JwtBearerSample/wwwroot/App/Views/Home.html
samples/JwtBearerSample/wwwroot/App/Views/TodoList.html
samples/JwtBearerSample/wwwroot/App/Views/UserData.html
samples/JwtBearerSample/wwwroot/index.html
samples/JwtBearerSample/wwwroot/web.config

#574 @HaoK @brentschmaltz @muratg 
Liberally borrowed the SPA code from https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp
This will give us somewhere to work on #411 and #555 via multi-tenant JWT.

Add a JwtBearer sample.

---

samples/JwtBearerSample/Startup.cs
samples/OpenIdConnectSample/Properties/launchSettings.json
samples/SocialSample/Startup.cs
src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationHandler.cs
src/Microsoft.AspNet.Authentication.JwtBearer/Events/JwtBearerEvents.cs
src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerHandler.cs
src/Microsoft.AspNet.Authentication.OAuth/OAuthHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNet.Authentication.Twitter/TwitterHandler.cs
src/Microsoft.AspNet.Authentication/AuthenticateResult.cs
src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNet.Authentication/Events/FailureContext.cs
src/Microsoft.AspNet.Authentication/Events/IRemoteAuthenticationEvents.cs
src/Microsoft.AspNet.Authentication/Events/RemoteAuthenticationEvents.cs
src/Microsoft.AspNet.Authentication/RemoteAuthenticationHandler.cs
test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs

Make SkipToNextMiddleware work on events.

---

samples/JwtBearerSample/Startup.cs
samples/JwtBearerSample/project.json
samples/OpenIdConnectSample/Startup.cs
samples/OpenIdConnectSample/project.json
samples/SocialSample/Startup.cs
samples/SocialSample/config.json
samples/SocialSample/project.json

#593 @HaoK @PinpointTownes @muratg

Convert samples to use UserSecrets.

---

samples/CookieSample/Properties/launchSettings.json
samples/CookieSample/Startup.cs
samples/CookieSample/hosting.json
samples/CookieSample/project.json
samples/CookieSessionSample/Properties/launchSettings.json
samples/CookieSessionSample/Startup.cs
samples/CookieSessionSample/hosting.json
samples/CookieSessionSample/project.json
samples/JwtBearerSample/Startup.cs
samples/JwtBearerSample/hosting.json
samples/JwtBearerSample/project.json
samples/OpenIdConnectSample/Properties/launchSettings.json
samples/OpenIdConnectSample/Startup.cs
samples/OpenIdConnectSample/hosting.json
samples/OpenIdConnectSample/project.json
samples/SocialSample/Properties/launchSettings.json
samples/SocialSample/Startup.cs
samples/SocialSample/hosting.json
samples/SocialSample/project.json
test/Microsoft.AspNet.Authentication.Test/Cookies/CookieMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/Facebook/FacebookMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/Google/GoogleMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/MicrosoftAccount/MicrosoftAccountMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/Twitter/TwitterMiddlewareTests.cs
test/Microsoft.AspNet.CookiePolicy.Test/CookiePolicyTests.cs
test/Microsoft.Owin.Security.Cookies.Interop.Test/TicketInteropTests.cs

Reacting to https://github.com/aspnet/Hosting/pull/521

Reacting to new Hosting API

---

src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerHandler.cs
src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerOptions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
test/Microsoft.AspNet.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs
test/Microsoft.AspNet.Authentication.Test/OpenIdConnect/OpenIdConnectHandlerTests.cs

Just an FYI: @muratg @brentschmaltz @tushargupta51

React to IdentityModel namespace changes.

---

samples/SocialSample/Startup.cs
src/Microsoft.AspNet.Authentication.Cookies/CookieAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.Facebook/FacebookAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.Google/GoogleAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.MicrosoftAccount/MicrosoftAccountAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.OAuth/OAuthAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.OAuth/OAuthOptions.cs
src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication.Twitter/TwitterAppBuilderExtensions.cs
src/Microsoft.AspNet.Authentication/ClaimsTransformationAppBuilderExtensions.cs
src/Microsoft.AspNet.CookiePolicy/CookiePolicyAppBuilderExtensions.cs
test/Microsoft.AspNet.Authentication.Test/Cookies/CookieMiddlewareTests.cs

Standardizing ConfigureOptions to lambda https://github.com/aspnet/Coherence-Signed/issues/144

Stardardizing middleware to use ConfigureOption lambda

---

src/Microsoft.AspNet.Authorization/AuthorizationPolicy.cs
test/Microsoft.AspNet.Authorization.Test/AuthorizationPolicyFacts.cs

Fix missing Trim in Roles and Schemes split

---

.gitattributes
.gitignore
.travis.yml
appveyor.yml
build.cmd
build.sh
makefile.shade
test/Microsoft.AspNet.Authentication.Test/project.json
test/Microsoft.AspNet.Authorization.Test/project.json
test/Microsoft.AspNet.CookiePolicy.Test/project.json
test/Microsoft.Owin.Security.Interop.Test/project.json

Build with dotnet

---

src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs
src/Microsoft.AspNetCore.Authentication.OAuth/OAuthOptions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/Cookies/CookieMiddlewareTests.cs
test/Microsoft.AspNetCore.Authentication.Test/Facebook/FacebookMiddlewareTests.cs
test/Microsoft.AspNetCore.Authentication.Test/Google/GoogleMiddlewareTests.cs
test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccount/MicrosoftAccountMiddlewareTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
test/Microsoft.AspNetCore.Authentication.Test/Transaction.cs
test/Microsoft.AspNetCore.CookiePolicy.Test/Transaction.cs
test/Microsoft.Owin.Security.Interop.Test/CookieInteropTests.cs
test/Microsoft.Owin.Security.Interop.Test/TicketInteropTests.cs

#526 Change from storing expires_in to calculating expires_at.
@leastprivilege @brentschmaltz @PinpointTownes 
#632 Save twitters access token secret as a claim.
@SHAGGAR 
@muratg @HaoK

Change from storing expires_in to calculating expires_at. Update twitter.

---

src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs

https://github.com/aspnet/Logging/issues/331

React to Logging API changes

---

src/Microsoft.AspNetCore.Authentication.Cookies/project.json
src/Microsoft.AspNetCore.Authentication.Facebook/project.json
src/Microsoft.AspNetCore.Authentication.OAuth/project.json

Updated Json.Net versions

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs

Fixes https://github.com/aspnet/Security/issues/729
cc @PinpointTownes @Tratcher

SaveTokens in OIDC

---

src/Microsoft.AspNetCore.Authentication.Facebook/FacebookOptions.cs

This PR seems to have support for inclusion in RC2.
Discussed at length here https://github.com/aspnet/Security/issues/688#issuecomment-194053590

Add GivenName and Surname default claims to FacebookOptions

---

src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs

unregister auth handlers during unwind.

---

src/Microsoft.AspNetCore.Authentication.OAuth/project.json

Updated Json.Net version

---

test/Microsoft.Owin.Security.Interop.Test/CookieInteropTests.cs

Reacting to DataProtection changes

---

samples/OpenIdConnect.AzureAdSample/project.json
src/Microsoft.AspNetCore.Authentication.OAuth/project.json
src/Microsoft.AspNetCore.Authentication.Twitter/project.json

Cleanup transitive dependencies

---

src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication.Twitter/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs
src/Microsoft.AspNetCore.Authorization/LoggingExtensions.cs

[Fixes #532] Replace hard-coded logging event ids with a class of consts

---

src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs

Guard against null ref

---

samples/CookieSample/Startup.cs
samples/CookieSessionSample/Startup.cs
samples/JwtBearerSample/Startup.cs
samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/OpenIdConnectSample/Startup.cs
samples/SocialSample/Startup.cs

Fix a typo from my previous commit. FYI only. Merging immediately to fix the build.

Fix typo when migrating to ANCM

---

samples/SocialSample/Startup.cs

- aspnet/KestrelHttpServer#720

React to Kestrel config changes

---

samples/CookieSample/project.json
samples/CookieSessionSample/project.json
samples/JwtBearerSample/project.json
samples/OpenIdConnectSample/project.json
samples/SocialSample/project.json
test/Microsoft.AspNetCore.Authentication.Test/project.json
test/Microsoft.AspNetCore.Authorization.Test/project.json
test/Microsoft.AspNetCore.CookiePolicy.Test/project.json

Migrate tests/samples/tools to portable

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs

#744 @Eilon @DamianEdwards - Please approve for RC2
@brentschmaltz @vibronet @rustd @phenning

Change OIDC's default ResponseType to IdToken.

---

samples/CookieSample/project.json
samples/CookieSample/web.config
samples/CookieSessionSample/project.json
samples/CookieSessionSample/web.config
samples/JwtBearerSample/project.json
samples/JwtBearerSample/web.config
samples/OpenIdConnect.AzureAdSample/project.json
samples/OpenIdConnect.AzureAdSample/web.config
samples/OpenIdConnectSample/project.json
samples/OpenIdConnectSample/web.config
samples/SocialSample/project.json
samples/SocialSample/web.config

Update web.config and add publish tool

---

samples/SocialSample/Startup.cs
samples/SocialSample/config.json
src/Microsoft.AspNetCore.Authentication.Twitter/Events/TwitterCreatingTicketContext.cs
src/Microsoft.AspNetCore.Authentication.Twitter/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterOptions.cs
src/Microsoft.AspNetCore.Authentication.Twitter/project.json

#765 @HaoK @muratg 
And some cleanup of the twitter handler and sample code.

Retrieve the email address from Twitter.

---

samples/OpenIdConnect.AzureAdSample/project.json
samples/OpenIdConnectSample/project.json
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/project.json
test/Microsoft.AspNetCore.Authentication.Test/project.json

#808 @danroth27 @Eilon @DamianEdwards @muratg @vibronet @brentschmaltz @tushargupta51

Update OIDC to v1.0

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectMiddleware.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs

Add argument validation

---

samples/CookieSample/Program.cs
samples/CookieSample/Properties/launchSettings.json
samples/CookieSessionSample/Program.cs
samples/CookieSessionSample/Properties/launchSettings.json
samples/JwtBearerSample/Program.cs
samples/JwtBearerSample/Properties/launchSettings.json
samples/OpenIdConnect.AzureAdSample/AuthPropertiesTokenCache.cs
samples/OpenIdConnect.AzureAdSample/Program.cs
samples/OpenIdConnect.AzureAdSample/Properties/launchSettings.json
samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/OpenIdConnect.AzureAdSample/project.json
samples/SocialSample/Properties/launchSettings.json

@vibronet @HaoK @rustd @brentschmaltz @tushargupta51

Update the OIDC AzureAd sample.

---

samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/OpenIdConnect.AzureAdSample/project.json

Update sample ADAL dependency

---

src/Microsoft.AspNetCore.Authorization/AuthorizationHandler.cs
src/Microsoft.AspNetCore.Authorization/AuthorizationHandlerContext.cs
src/Microsoft.AspNetCore.Authorization/AuthorizationOptions.cs
src/Microsoft.AspNetCore.Authorization/AuthorizationPolicy.cs
src/Microsoft.AspNetCore.Authorization/AuthorizationPolicyBuilder.cs
src/Microsoft.AspNetCore.Authorization/AuthorizationServiceExtensions.cs
src/Microsoft.AspNetCore.Authorization/AuthorizeAttribute.cs
src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationPolicyProvider.cs
src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs
src/Microsoft.AspNetCore.Authorization/IAllowAnonymous.cs
src/Microsoft.AspNetCore.Authorization/IAuthorizationPolicyProvider.cs
src/Microsoft.AspNetCore.Authorization/IAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/IAuthorizationService.cs
src/Microsoft.AspNetCore.Authorization/IAuthorizeData.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/AssertionRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/ClaimsAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/DenyAnonymousAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/NameAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/OperationAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/PassThroughAuthorizationHandler.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/RolesAuthorizationRequirement.cs

@Eilon please to be squirreling

Doc Comments

---

src/Microsoft.AspNetCore.Authorization/IAuthorizationService.cs

Fixes https://github.com/aspnet/Security/issues/816
cc @Eilon @blowdart

Doc comment update

---

test/Microsoft.AspNetCore.Authentication.Test/project.json
test/Microsoft.AspNetCore.Authorization.Test/project.json
test/Microsoft.AspNetCore.CookiePolicy.Test/project.json
test/Microsoft.Owin.Security.Interop.Test/project.json

Updating to RTM builds of xunit and Moq

---

samples/OpenIdConnect.AzureAdSample/Program.cs
samples/OpenIdConnect.AzureAdSample/Readme.md
samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/OpenIdConnect.AzureAdSample/project.json

Update the OpenIdConnect Azure Sample

---

samples/OpenIdConnectSample/Readme.md

* fixed broken link
* improved formatting
* added missing full stops

Improve sample README

---

src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs

Update comments in RemoteAuthenticationOptions

---

src/Microsoft.AspNetCore.Authentication/TokenExtensions.cs
test/Microsoft.AspNetCore.Authentication.Test/TokenExtensionTests.cs

Fixes https://github.com/aspnet/Security/issues/916
@Tratcher

Add new UpdateTokenValue API

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs

JwtBearer Token: Catch exception during unauthorized flow

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/Cookies/CookieMiddlewareTests.cs

Allow absolute uri in authentication properties for cookie auth redirect

---

samples/OpenIdConnect.AzureAdSample/Startup.cs

1. Add signout remote scenario
2. Use bootstrap to enhance the view
3. Improve readability
Effect:

Refine OIDC sample

---

samples/OpenIdConnect.AzureAdSample/Startup.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectMiddlewareTests.cs

Address issue #743, and react to recent AAD OIDC sign out flow change.

Update OIDC signout flow

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/Cookies/CookieMiddlewareTests.cs

Issue: https://github.com/aspnet/Security/issues/949

Ignore null ExpiresUtc property in RequestRefresh

---

src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs
src/Microsoft.AspNetCore.Authentication.Cookies/project.json
src/Microsoft.AspNetCore.Authentication.JwtBearer/Events/JwtBearerEvents.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/project.json
src/Microsoft.AspNetCore.Authentication.OAuth/Events/OAuthEvents.cs
src/Microsoft.AspNetCore.Authentication.OAuth/project.json
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/OpenIdConnectEvents.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/project.json
src/Microsoft.AspNetCore.Authentication.Twitter/Events/TwitterEvents.cs
src/Microsoft.AspNetCore.Authentication.Twitter/project.json
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/ClaimsTransformationHandler.cs
src/Microsoft.AspNetCore.Authentication/Events/RemoteAuthenticationEvents.cs
src/Microsoft.AspNetCore.Authentication/project.json
src/Microsoft.AspNetCore.Authorization/Infrastructure/ClaimsAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/DenyAnonymousAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/NameAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/RolesAuthorizationRequirement.cs
src/Microsoft.AspNetCore.Authorization/project.json

Instead of Task.FromResult(0)
@pranavkm

Use TaskCache class from Microsoft.Extensions.TaskCache.Sources

---

src/Microsoft.AspNetCore.Authentication.Twitter/project.json

Update Twitter auth package description

---

src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/Google/GoogleMiddlewareTests.cs

Rename Google auth endpoint parameter approval_prompt to prompt

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/LoggingExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs

Log the error inforamtion when redeem auth code

---

NuGetPackageVerifier.json

@kichalla @ajaybhargavb @pranavkm

Add ChunkingCookieManager.Sources to NuGetPackageVerifier

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs

Cookie Auto: set properties back to ticket when using SessionStore

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Utility/ClaimsHelper.cs

Fix #976: Break claims value in array into multiple claims

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Utility/ClaimsHelper.cs

Fixes https://github.com/aspnet/Security/issues/998.
Note: the userinfo mechanism has currently no unit test.
To ensure the changes added by this PR work as intended, I used ASOS beta7. To test it yourself, you can use this snippet:
```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
Authority = "http://localhost:3304/",
ClientId = "client_id",
ResponseType = "id_token token",
GetClaimsFromUserInfoEndpoint = true,
RequireHttpsMetadata = false
});
```
```csharp
app.UseOpenIdConnectServer(options =>
{
options.AllowInsecureHttp = true;
options.SigningCredentials.AddEphemeralKey();
options.AuthorizationEndpointPath = "/connect/authorize";
options.UserinfoEndpointPath = "/connect/userinfo";
options.Provider.OnValidateAuthorizationRequest = context =>
{
context.Validate(); …
```

Update ClaimsHelper.AddClaimsToIdentity to infer the claim value type from the JSON token type

---

samples/JwtBearerSample/Startup.cs
samples/OpenIdConnectSample/Startup.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
src/Microsoft.AspNetCore.Authentication/AuthenticateResult.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/Events/BaseControlContext.cs
src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectEventTests.cs

I still need to try it with other events, other middleware, and add tests.

Honor OIDC's OnAuthenticationFailed HandleResponse()

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs

Revert breaking parameter rename

---

global.json
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/AuthenticationHandlerFacts.cs

Just moving https://github.com/aspnet/Security/pull/1063 to the rel/1.1.1 branch.
Also pinning the sdk version so we can build.

Revert challenge changes

---

samples/OpenIdConnect.AzureAdSample/OpenIdConnect.AzureAdSample.csproj
samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/SocialSample/Program.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/Microsoft.AspNetCore.Authentication.JwtBearer.csproj
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Microsoft.AspNetCore.Authentication.OpenIdConnect.csproj

Porting https://github.com/aspnet/Security/pull/1092 to dev

Update IdentityModel dependencies, fix samples

---

samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/OpenIdConnect.AzureAdSample/project.json
src/Microsoft.AspNetCore.Authentication.JwtBearer/project.json
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/project.json

Due to an MSRC. https://github.com/aspnet/Security/issues/1082
I'll do a different change for dev since it has already changed to csproj.

Update IdentityModel dependencies

---

src/Microsoft.AspNetCore.Authentication/project.json
src/Microsoft.AspNetCore.Authorization/project.json

Remove conflicting frameworkAssembly references

---

samples/SocialSample/Startup.cs

To avoid confusion when reading the code

Update of wrong variable name

---

samples/OpenIdConnect.AzureAdSample/Readme.md

Assuming DEVELOPMENMT should be DEVELOPMENT.

Fix typo in Azure AD sample README.md

---

build/dependencies.props
src/Microsoft.AspNetCore.Authentication.JwtBearer/Microsoft.AspNetCore.Authentication.JwtBearer.csproj
src/Microsoft.AspNetCore.Authentication.OAuth/Microsoft.AspNetCore.Authentication.OAuth.csproj
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Microsoft.AspNetCore.Authentication.OpenIdConnect.csproj
src/Microsoft.AspNetCore.Authorization/Microsoft.AspNetCore.Authorization.csproj
test/Microsoft.AspNetCore.CookiePolicy.Test/Microsoft.AspNetCore.CookiePolicy.Test.csproj

https://github.com/aspnet/Coherence/issues/175

Remove unnecessary package references

---

src/Microsoft.AspNetCore.Authentication.Cookies/Microsoft.AspNetCore.Authentication.Cookies.csproj
src/Microsoft.AspNetCore.Authentication.Cookies/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.Facebook/Microsoft.AspNetCore.Authentication.Facebook.csproj
src/Microsoft.AspNetCore.Authentication.Facebook/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.Google/Microsoft.AspNetCore.Authentication.Google.csproj
src/Microsoft.AspNetCore.Authentication.Google/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.JwtBearer/Microsoft.AspNetCore.Authentication.JwtBearer.csproj
src/Microsoft.AspNetCore.Authentication.JwtBearer/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/Microsoft.AspNetCore.Authentication.MicrosoftAccount.csproj
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.OAuth/Microsoft.AspNetCore.Authentication.OAuth.csproj
src/Microsoft.AspNetCore.Authentication.OAuth/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Microsoft.AspNetCore.Authentication.OpenIdConnect.csproj
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.Twitter/Microsoft.AspNetCore.Authentication.Twitter.csproj
src/Microsoft.AspNetCore.Authentication.Twitter/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication/Microsoft.AspNetCore.Authentication.csproj
src/Microsoft.AspNetCore.Authentication/breakingchanges.netcore.json

Reenable API check

---

src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/LoggingExtensions.cs

#1265 - Log auth failures

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieExtensions.cs
src/Microsoft.AspNetCore.Authentication.Facebook/FacebookExtensions.cs
src/Microsoft.AspNetCore.Authentication.Google/GoogleExtensions.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerExtensions.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountExtensions.cs
src/Microsoft.AspNetCore.Authentication.OAuth/OAuthExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectExtensions.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterExtensions.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs
test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs
test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs
test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccountTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs
test/Microsoft.AspNetCore.Authentication.Test/TwitterTests.cs

Fixes https://github.com/aspnet/Security/issues/1269
@Tratcher

Remove AddXyzAuth extension methods

---

src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs

#1208 IM will look at both the single value and the list, so we can simplify the code to always work with the list at our layer.

Clean up JWT and OIDC issuer handling

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs
src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountHandler.cs
src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/DynamicSchemeTests.cs

Added a basic test to ensure AuthenticationSchemeOptions are not recreated per request
Fixes https://github.com/aspnet/Security/issues/1282
@Tratcher

Switch to IOptionsMonitor

---

test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs
test/Microsoft.AspNetCore.Authentication.Test/DynamicSchemeTests.cs
test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs
test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs
test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccountTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/TestServerBuilder.cs

Fix tests to work with new default

---

src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs
test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs
test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs
test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccountTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/TestServerBuilder.cs

Add AddAuthentication(defaultScheme) overload

---

build/dependencies.props
samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/OpenIdConnectSample/Startup.cs

Some minor tweaks to to the samples found during manual testing due to Hao's recent changes.

Update IdentityModel versions to latest, fix samples.

---

samples/OpenIdConnect.AzureAdSample/Startup.cs
samples/SocialSample/Startup.cs
src/Microsoft.AspNetCore.Authentication.Cookies/CookieExtensions.cs
src/Microsoft.AspNetCore.Authentication.Facebook/FacebookDefaults.cs
src/Microsoft.AspNetCore.Authentication.Facebook/FacebookExtensions.cs
src/Microsoft.AspNetCore.Authentication.Google/GoogleDefaults.cs
src/Microsoft.AspNetCore.Authentication.Google/GoogleExtensions.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerExtensions.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountDefaults.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountExtensions.cs
src/Microsoft.AspNetCore.Authentication.OAuth/OAuthDefaults.cs
src/Microsoft.AspNetCore.Authentication.OAuth/OAuthExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectDefaults.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/breakingchanges.netcore.json
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterDefaults.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterExtensions.cs
test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs

#1319 @leastprivilege @PinpointTownes 
No change to defaults.

Add DisplayName overloads

---

src/Microsoft.AspNetCore.Authorization.Policy/IPolicyEvaluator.cs
src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs
test/Microsoft.AspNetCore.Authorization.Test/PolicyEvaluatorTests.cs

Fixed PR to be against rel 2.0
Fixes https://github.com/aspnet/Security/issues/1329
@davidfowl

AuthZ PolicyEvalutor should take resource

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.Facebook/FacebookAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.Google/GoogleAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.OAuth/OAuthAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectAppBuilderExtensions.cs
src/Microsoft.AspNetCore.Authentication.Twitter/TwitterAppBuilderExtensions.cs

Fixes https://github.com/aspnet/Security/issues/1334
@Tratcher @moozzyk

Update obsolete error

---

samples/OpenIdConnectSample/Startup.cs
samples/SocialSample/Startup.cs

Not actually planning to merge this yet, but I wanted to put it up here for discussion.
Not sure if there's a way to standardize this across our providers. Google followed the spec, but the others look harder. Twitter and Github tokens don't expire so there's no refresh. Facebook has their own refresh flow. I haven't found the right MSA docs yet.
https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension

Add sample for refresh tokens

---

test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/TestSettings.cs

#772 one more test scenario and more test code cleanup

Signout FormPost test

---

src/Microsoft.AspNetCore.Authentication.OAuth/Claims/ClaimAction.cs
src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs
src/Microsoft.AspNetCore.Authorization/IAuthorizationService.cs
src/Microsoft.AspNetCore.Authorization/Infrastructure/PassThroughAuthorizationHandler.cs

House Cleaning - Spell check and grammar. :shower:
:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***

House Cleaning - Spell check and grammar.

---

src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs

Removed useless checks

---

src/Microsoft.AspNetCore.Authentication.Facebook/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication.Google/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication.JwtBearer/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication.OAuth/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication.Twitter/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authentication/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Authorization/Properties/Resources.Designer.cs

Run build /t:resx to normalize the designer
@Tratcher

Cleanup resx

---

src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs

Fix comment, it's setting sign in scheme (old left-over from copy-paste?)

Fix comment

---

src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs

Fixes https://github.com/aspnet/Security/issues/1431
@Tratcher

Obsolete old AddSchemes

---

src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs
src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs
src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountHandler.cs

Corrected spelling and matched style of the exception message in the handler.

Cleaned up MicrosoftAccountHandler exception message

---

src/Microsoft.AspNetCore.Authentication/AuthenticationBuilder.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationSchemeOptions.cs
src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs
test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs

Fixes https://github.com/aspnet/Security/issues/1423
@Tratcher

Add Validate(scheme) and use for RemoteSignInScheme not self validation

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs

Fixes https://github.com/aspnet/Security/issues/1483
@Tratcher

Update cookie doc comments

---

test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectEventTests.cs

This is useful OIDC events test refactoring from an otherwise aborted PR (https://github.com/aspnet/Security/pull/1515). It makes it easier to add more events in the future.

Refactor OIDC event tests

---

test/Microsoft.AspNetCore.Authentication.Test/Microsoft.AspNetCore.Authentication.Test.csproj

Remove redundant references

---

src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs

#1448 @PinpointTownes 
We don't need this code, IdentityModel can do it for us.

OIDC: Use IdentityModel redirect form generator

---

src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyOptions.cs
test/Microsoft.AspNetCore.CookiePolicy.Test/CookieConsentTests.cs

Raise the CookiePolicy consent cookie lifetime to one year

---

samples/JwtBearerSample/Startup.cs

#1613 The sample was not updated after the 2.0 refactors. The handler cannot directly return an error response, it must rely on a secondary component for that.

Update JwtBearer sample error handling

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Authentication/AuthenticationSchemeOptions.cs
test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs
test/Microsoft.AspNetCore.Authentication.Test/FacebookTests.cs
test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs
test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs
test/Microsoft.AspNetCore.Authentication.Test/MicrosoftAccountTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OAuthTests.cs
test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectConfigurationTests.cs
test/Microsoft.AspNetCore.Authentication.Test/TestHandlers.cs
test/Microsoft.AspNetCore.Authentication.Test/TwitterTests.cs

Replaces https://github.com/aspnet/Security/pull/1550
This PR will only focus on adding the new forwarding behavior.
The fate of pure VirtualAuthenticationHandlers/behavior will be addressed in a separate PR.

Add scheme forwarding (authN policies)

---

src/Microsoft.AspNetCore.Authentication.Google/GoogleDefaults.cs
test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs

Update google auth endpoint to v2

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs

#1607 When we are asked to refresh a cookie either via sliding refresh or manual, clone the ticket so that any app modifications are not persisted.
@NinoFloris

Clone tickets for refresh

---

test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs

#640 The hardcoded token had expired so instead we create a token on demand.

Rewrite JwtBearer token test

---

samples/CookiePolicySample/Startup.cs

Cookie Policy sample essential cookie

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs

Fix for https://github.com/aspnet/Security/issues/1788
CookieCanBeUpdatedByValidatorDuringRefresh is the new regression test that fails for the identity scenario.

Fix cookie regression

---

src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs
test/Microsoft.AspNetCore.Authentication.Test/CookieTests.cs

Hand merge since bot merge has conflicts
@natemcmaster

Merge release/2.2 => master

---

samples/JwtBearerSample/wwwroot/index.html

Sweet #Hacktoberfest clippy t-shirt, come to papa.

Added missing Div tag in JWTBearer Sample index.html

---

build/dependencies.props
test/Microsoft.AspNetCore.Authorization.Test/AuthorizationMiddlewareTests.cs
test/Microsoft.AspNetCore.Authorization.Test/Microsoft.AspNetCore.Authorization.Test.csproj

Port of relevant authz filter tests. Will add more to cover scenarios specific to the new authz middleware.

[WIP] Add AuthorizationMiddleware tests
